name: teacher_admin
description: "Teacher Attendance Web Admin Panel"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.0
  dio: ^5.8.0+1
  flutter_secure_storage: ^9.2.4
  go_router: ^14.8.1
  intl: ^0.20.2
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
